model:
  kernel_size: 3
  num_layers: 7

training:
  batch_size: 6
  learning_rate: 1e-04
  epochs: 50
  alpha: 0.1
  early_stopping_patience: 12
  val_split: 0.10
  split_seed: 123
  use_gpu: true

paths:
  h5_glob: "./data/converted_h5/MS30013.h5"
  output_dir: "./results"
  csv_subdir: "csv"

data:
  samples_per_file: 384
  crop_size: [256, 256]
  input_channel: 0
  input_key: "raw_channels"
  target_key: "spectrum"
